### ISSUE TITLE
Error when opening pbix file

### ISSUE THREAD

**Issue by FlorianOhms** [tabulartools/pbi-explorer#50]
### Describe the problem

Error message encountered when trying to open a pbix file. Error message states object reference error (see additional context for full error message)

### PBI Explorer

0.4.1

### Power BI

Power BI Desktop Version October 2023, Version: 2.122.746.0 64-bit

### Windows

Microsoft Windows 11 Pro, Version 10.0.22621 Build 22621

### Steps to reproduce the behavior

1. Open PBI Explorer

2. Click "open in inspector"

### Screenshots

![2023-10-17_15h36_28](https://github.com/tabulartools/pbi-explorer/assets/147702179/c0174128-cc6a-4c19-b4b8-56f98af74cbf)

### Anything else ?

************** Exception Text **************

System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiExplorer.Shared.ReportElementHelper.GetFriendlyName(ReportElement reportElement)
   at PbiExplorer.Shared.Services.ReportInspectionService.GetElementName(Object element)
   at PbiExplorer.UI.Views.ReportInspectorView.VirtualTreeGetCellValue(Object sender, VirtualTreeGetCellValueInfo e)
   at DevExpress.XtraTreeList.TreeList.TreeListVirtualDataHelper.GetCellDataViaEvent(Object node, TreeListColumn column, Boolean isCheckState)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.GetCellsData(Object node, IVirtualTreeListData parent)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateRootNodes()
   at DevExpress.XtraTreeList.TreeList.LoadNodes()
   at DevExpress.XtraTreeList.TreeList.DoDataSourceChanged()
   at DevExpress.XtraTreeList.TreeList.LoadDataSource(Boolean reload, Boolean forceLoadNodes)
   at DevExpress.XtraTreeList.TreeList.UpdateDataSourceOnChangeDataSource()
   at PbiExplorer.UI.Views.ReportInspectorView.AppInspectorFileLoaded(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer
    Assembly-Version: 0.4.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Utils.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Thread
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ObjectModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Uri
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Cryptography
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Xml
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.WebClient
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.Desktop.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Drawing.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Compression
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraBars.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraEditors.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Memory
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Annotations
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraLayout.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Printing.v23.1.Core
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer.Shared
    Assembly-Version: 0.4.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraTreeList.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraVerticalGrid.v23.1
    Assembly-Version: 23.1.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-Version: 1.0.1774.30.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-Version: 1.0.1774.30.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 13.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Http
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Security
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Quic
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Sockets
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Claims
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json.Schema
    Assembly-Version: 3.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Numerics
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Data.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Packaging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiTools.ReportModel
    Assembly-Version: 0.4.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog
    Assembly-Version: 2.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Tasks
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------

************** JIT-Debuggen **************

**Comment by DBojsen** [comment]
Thank you for reporting @FlorianOhms 

If you can share a pbit file (without data), we would appreciate it.  You can send it to support@tabulartools.com.

**Comment by DBojsen** [comment]
This is fixed in BETA4 (0.5.1).  Get it at pbiexplorer.com.

**Comment by FlorianOhms** [comment]
Unfortunately, in 0.5.1. I still get an error. However, it seems to load at least a part of the the dataset now and gets the error during the loading.

Attached, the new error message. I will see if I can get you the file.

************** Ausnahmetext **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiExplorer.Shared.ReportElementHelper.GetFriendlyName(ReportElement reportElement)
   at PbiExplorer.Shared.Services.ReportInspectionService.GetElementName(Object element)
   at PbiExplorer.UI.Views.ReportInspectorView.VirtualTreeGetCellValue(Object sender, VirtualTreeGetCellValueInfo e)
   at DevExpress.XtraTreeList.TreeList.TreeListVirtualDataHelper.GetCellDataViaEvent(Object node, TreeListColumn column, Boolean isCheckState)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.GetCellsData(Object node, IVirtualTreeListData parent)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateRootNodes()
   at DevExpress.XtraTreeList.TreeList.LoadNodes()
   at DevExpress.XtraTreeList.TreeList.DoDataSourceChanged()
   at DevExpress.XtraTreeList.TreeList.LoadDataSource(Boolean reload, Boolean forceLoadNodes)
   at DevExpress.XtraTreeList.TreeList.UpdateDataSourceOnChangeDataSource()
   at PbiExplorer.UI.Views.ReportInspectorView.AppOnInspectorFileLoaded(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)


************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer
    Assembly-Version: 0.5.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Utils.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.ApplicationInsights
    Assembly-Version: 2.21.0.429.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog
    Assembly-Version: 2.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Extensions.Hosting
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Uri
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.Json
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Extensions.Logging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Sinks.ApplicationInsights
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Xml.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Xml
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer.BestPracticeAnalyzer
    Assembly-Version: 0.5.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ObjectModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 13.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Numerics
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Data.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiTools.ReportModel
    Assembly-Version: 0.5.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Memory
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Drawing.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Thread
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Cryptography
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.WebClient
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.Desktop.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Compression
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraLayout.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer.Shared
    Assembly-Version: 0.5.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraTreeList.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraEditors.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Printing.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraVerticalGrid.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-Version: 1.0.2088.41.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-Version: 1.0.2088.41.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Annotations
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraBars.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Http
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Security
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Quic
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Sockets
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Claims
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json.Schema
    Assembly-Version: 3.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Packaging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Queryable
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Dynamic.Core
    Assembly-Version: 1.3.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Writer
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.XmlSerializer
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.EventLog
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Console
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.XDocument
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Formats.Asn1
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Requests
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
WindowsBase
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.AccessControl
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Sparkline.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ServiceModel.Primitives
    Assembly-Version: 4.10.2.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.ServiceModel
    Assembly-Version: 4.10.2.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Pdf.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Tasks
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.NetworkInformation
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.Encodings.Web
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Intrinsics
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------

************** JIT-Debuggen **************

**Comment by DBojsen** [comment]
Hi @FlorianOhms 

Sorry about that - I'll reopen

**Comment by DBojsen** [comment]
This should be fixed with BETA5 (0.6.1) which we released yesterday.
If you still have the issue, please reopen.

**Comment by FlorianOhms** [comment]
Unfortunately the issue is still present in 0.6.1. As dataset contains intellectual property, I cannot provide it right now, sorry for that.

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiExplorer.Shared.ReportElementHelper.GetFriendlyName(ReportElement reportElement)
   at PbiExplorer.Shared.Services.ReportInspectionService.GetElementName(Object element)
   at PbiExplorer.UI.Views.ReportInspectorView.VirtualTreeGetCellValue(Object sender, VirtualTreeGetCellValueInfo e)
   at DevExpress.XtraTreeList.TreeList.TreeListVirtualDataHelper.GetCellDataViaEvent(Object node, TreeListColumn column, Boolean isCheckState)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.GetCellsData(Object node, IVirtualTreeListData parent)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateChildren(VirtualDataRow parentRow, Boolean recursive)
   at DevExpress.XtraTreeList.Data.TreeListVirtualData.CreateRootNodes()
   at DevExpress.XtraTreeList.TreeList.LoadNodes()
   at DevExpress.XtraTreeList.TreeList.DoDataSourceChanged()
   at DevExpress.XtraTreeList.TreeList.LoadDataSource(Boolean reload, Boolean forceLoadNodes)
   at DevExpress.XtraTreeList.TreeList.OnLoadedCore(Boolean forceUpdateFilter)
   at DevExpress.XtraTreeList.TreeList.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at DevExpress.XtraLayout.LayoutControl.OnVisibleChanged(EventArgs e)
   at DevExpress.XtraLayout.LayoutControl.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at DevExpress.XtraBars.Navigation.NavigationPageBase.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at DevExpress.XtraBars.Navigation.NavigationFrame.SetSelectedPageCore(INavigationPageBase value)
   at DevExpress.XtraBars.Navigation.NavigationFrame.set_SelectedPageCore(INavigationPageBase value)
   at PbiExplorer.UI.Main.setInspectorViewActive()
   at PbiExplorer.UI.Controllers.App.OnFileLoaded()
   at PbiExplorer.UI.Controllers.App.OpenFile(String path)
   at PbiExplorer.UI.Main.btnOpenInspector_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraUserControl.BaseWndProc(Message& m)
   at DevExpress.XtraEditors.XtraUserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer
    Assembly-Version: 0.6.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Utils.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Drawing.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.ApplicationInsights
    Assembly-Version: 2.21.0.429.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog
    Assembly-Version: 2.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Extensions.Hosting
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Uri
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.Json
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Extensions.Logging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Sinks.ApplicationInsights
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Serilog.Enrichers.Sensitive
    Assembly-Version: 1.7.3.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Xml.Linq
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.Xml
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer.BestPracticeAnalyzer
    Assembly-Version: 0.6.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ObjectModel
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 13.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Numerics
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Data.Common
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiTools.ReportModel
    Assembly-Version: 0.6.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Memory
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Drawing.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Thread
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Cryptography
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.WebClient
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Data.Desktop.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Compression
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Registry
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraLayout.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraTreeList.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
PbiExplorer.Shared
    Assembly-Version: 0.6.1.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraEditors.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Printing.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraVerticalGrid.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-Version: 1.0.2088.41.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-Version: 1.0.2088.41.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ComponentModel.Annotations
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.XtraBars.v23.1
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Runtime.Loader
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Http
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Security
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Quic
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Sockets
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.Claims
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
Newtonsoft.Json.Schema
    Assembly-Version: 3.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Windows.Extensions
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.Packaging
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Queryable
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Linq.Dynamic.Core
    Assembly-Version: 1.3.5.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Resources.Writer
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.XmlSerializer
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Diagnostics.EventLog
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Console
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Xml.XDocument
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Formats.Asn1
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.Requests
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
WindowsBase
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Security.AccessControl
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Sparkline.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.ServiceModel.Primitives
    Assembly-Version: 4.10.2.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Private.ServiceModel
    Assembly-Version: 4.10.2.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
DevExpress.Pdf.v23.1.Core
    Assembly-Version: 23.1.6.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Threading.Tasks
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------
System.Net.NetworkInformation
    Assembly-Version: 7.0.0.0.
    Win32-Version: n/v.
    CodeBase: .
----------------------------------------

************** JIT-Debuggen **************
